project:
  type: website
  output-dir: docs
website:
  title: "REDEC"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: Geomatic backoffice
        menu:
          - href: case38.qmd  
            text: "Isère (38)"   
          - href: case49.qmd  
            text: "Maine-et-Loire (49)"  
          - href: case80.qmd  
            text: "Somme (80)"               
          - href: case94.qmd  
            text: "Val-de-Marne (94)"
      - text: Visualization tools
        menu:
          - href: gerry38.qmd  
            text: "Isère (38)"   
          - href: gerry49.qmd  
            text: "Maine-et-Loire (49)"  
          - href: gerry80.qmd  
            text: "Somme (80)"               
          - href: gerry94.qmd  
            text: "Val-de-Marne (94)"           
      - text: Redistricting methods
        menu:
          - href: exp001.qmd  
            text: "k-means in demographic space"              
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/SMA
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2026, Claude Grasland, ANR Project REDEC
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


